project_name: hypr-kbd-layout
before:
  hooks:
    - go mod tidy
archives:
  - format: binary
builds:
  - main: "."
    mod_timestamp: '{{ .CommitTimestamp }}'
    goos:
      - linux
    goarch:
      - amd64
      - arm
    tags:
      - netgo
      - osusergo
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w -extldflags '-static'
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  name_template: 'v{{ .Version }}'
  make_latest: true

nfpms:
  - vendor: labi-le


    # Your app's homepage.
    homepage: https://github.com/labi-le/belphegor

    # Your app's maintainer (probably you).
    maintainer: labi-le <i@labile.cc>

    # Your app's description.
    description: |-
      keyboard layout plugin waybar

    # Your app's license.
    license: MIT

    # Formats to be generated.
    formats:
      - deb
      - rpm
      - archlinux

    # Packages your package recommends installing. (overridable)
    dependencies:
      - waybar
      - hyprland

    version_metadata: git